Update native-build.yml

diff --git a/.github/workflows/native-build.yml b/.github/workflows/native-build.yml
--- a/.github/workflows/native-build.yml
+++ b/.github/workflows/native-build.yml
@@ -49,15 +49,29 @@ jobs:
         id: create-adm-va
         with:
           command: 'adm vulnerability-audit create --knowledge-base-id=${{ secrets.ADM_KB }} --compartment-id=${{ secrets.ADM_VA_COMPART }} --display-name="native-hello-world" --build-type="MAVEN" --application-dependencies=file://target/NativeHelloWorld.app-deps.json'
-          query: "data.id"
+          query: "[data.id]"
           silent: false
           
-#      - name: Get ADM Vuln.Audit Result
-#        id: get-adm-va
-#        run: |
-#          while [ $(oci adm vulnerability-audit get --vulnerability-audit-id=${{ steps.create-adm-va.outputs.output }} | jq '.data.lifecycle-state') == "CREATING" ]; do sleep 10; done
-#          oci adm vulnerability-audit get --vulnerability-audit-id=${{ steps.create-adm-va.outputs.output }} >> $GITHUB_OUTPUT
+      - name: ADM Wait for VA (60s)
+        id: adm-wait-va
+        run: |
+          sleep 60s          
           
-#      - name: Display the Vuln.Audit  
-#        run: |
-#          echo ${{ steps.get-adm-va.outputs.output }} | jq .
+      - name: GET ADM Vuln.Audit
+        uses: oracle-actions/run-oci-cli-command@v1.1.1
+        id: get-adm-va
+        with:
+          command: "adm vulnerability-audit get --vulnerability-audit-id=${{ steps.create-adm-va.outputs.raw_output }}"
+          query: "data"
+          
+      - name: Evaluate Vuln.Audit
+        run: |
+          VA_RESULT=$(echo ${{ steps.get-adm-va.outputs.output }} | jq -jr '."is-success",."lifecycle-state"')
+          if [ "$VA_RESULT" != "trueACTIVE" ]; then
+            echo "# FAILED Vulnerability Audit" >> $GITHUB_STEP_SUMMARY
+            echo "## Vulnerability Audit OCID: ${{ env.ADM_VA_ID }}" >> $GITHUB_STEP_SUMMARY
+            echo "oci adm vulnerability-audit get --vulnerability-audit-id=${{ env.ADM_VA_ID }}" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo "### PASSED Vulnerability Audit :rocket:" >> $GITHUB_STEP_SUMMARY
+          fi  
